language: python
python:
  - "3.6"
install:
  - wget https://github.com/jgm/pandoc/releases/download/2.8.1/pandoc-2.8.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.8.1-1-amd64.deb
  - pandoc -v
  - pip install -e .[test]
  - pip install black
  - pip install pylint
  - pip install coverage
  - pip install coveralls
script:
  - black --check pandoc_beamer_arrow.py setup.py tests/test_arrow.py
  - pylint pandoc_beamer_arrow.py setup.py
  - coverage run -a --source=pandoc_beamer_arrow setup.py test
after_success:
  - coveralls

